version: 3.0.0-rc2-{build}
branches:
  only:
  - develop
skip_tags: true
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  project: EDDI.sln
  verbosity: minimal
test:
  categories:
    except:
    - Speech
    - DocGen
    - Network

# CodeCov + Appveyor example: https://github.com/ceddlyburge/codecov-on-appveyor/blob/master/appveyor.yml
# use codecov python script. Requires python to be available, which it is on AppVeyor machine image
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.2.0\tools\xunit.console.x86.exe" -targetargs:"Tests\bin\Debug\Tests.dll -noshadow" -output:".\coverage.xml" -filter:"+[SystemUnderTest*]* -[Tests*]*".\EDDI_coverage.xml"

 # use codecov python package. Requires python to be available, which it is on AppVeyor machine image, and then we have to install the codecov package
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"