version: 3.0.0-rc2-{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  project: EDDI.sln
  verbosity: minimal
test:
  categories:
    except:
    - Speech
    - DocGen
    - Network


# CodeCov + Appveyor example: https://github.com/ceddlyburge/codecov-on-appveyor/blob/master/appveyor.yml
test_script:
- .\packages\<ADD PATH>\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Tests\bin\Debug\Tests.dll -noshadow" -filter:"+[EDDI*]* -[UnitTests*]*" -output:".\EDDI_coverage.xml"
- .\packages\<ADD PATH>\codecov.exe -f "EDDI_coverage.xml"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "EDDI_coverage.xml" -t c0cc9048-1cdc-464b-b2fa-dac79464e1c4